name: Generate Doxy
on:
    push:
        paths:
          - 'lib/**'
          - '*.md'
          - '*.doxy'
          - 'res/**'
          - '.github/workflows/doxy.yml'

jobs:
    doc:
        name: Generate Doxy
        runs-on: ubuntu-latest
        
        steps:
            ## 检出工程
            - uses: actions/checkout@v3
              with: 
                submodules: 'true'
                
            ## 配置环境
            - run: git config --global user.name github-actions[bot]
            - run: git config --global user.email github-actions[bot]@users.noreply.github.com
            - run: git config --global --add safe.directory /github/workspace
            - run: sudo apt-get install graphviz -y
            - run: wget https://github.com/doxygen/doxygen/releases/download/Release_1_9_7/doxygen-1.9.7.linux.bin.tar.gz
            - run: tar -zxvf ./doxygen-1.9.7.linux.bin.tar.gz
            - run: rm -f ./doxygen-1.9.7.linux.bin.tar.gz
            - run: chmod -R 777 ./doxygen-1.9.7/bin/

            ## 生成文档
            - run: ./doxygen-1.9.7/bin/doxygen .doxy
            - run: rm -rf ./doxygen-1.9.7
            - run: mkdir ./.html/res/
            - run: cp ./res/* ./.html/res/
            - run: cp -r `find ./ -mindepth 3 -maxdepth 3 -name 'res'` ./.html/
            - run: git add ./.html
            - run: git stash save ./.html

            ## 切换分支
            - run: git fetch origin
            - run: git checkout gh-pages
            
            ## 清理目录
            - run: rm -rf ./lib
            - run: rm -rf ./res
            - run: git rm -rf *
            - run: git commit -m '[Doxy] commit cleanup'

            ## 移动文档
            - run: git stash pop
            - run: git commit -m '[Doxy] commit temporary'
            - run: mv ./.html/* ./
            - run: git rm -rf ./.html
            
            ## 创建文件（使得页面文件包含'_'的可以被访问）
            - run: touch .nojekyll

            ## 创建CNAME
            - run: touch ./CNAME && echo -e "go.eframework.cn" >> ./CNAME
            
            ## 推送文档
            - run: git add ./
            - run: git commit -m '[Doxy] commit product'
            - run: git push
